// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase config cho [mhx-attendance-dev].
/// Nền tảng hỗ trợ: Android, Windows (và Web nếu bật sau này).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'MHX Attendance hiện chỉ hỗ trợ Android và Windows.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPMHmOvK_NundTRLLYkoppIUSk7sVOqL8',
    appId: '1:971546956248:web:67b339de93a847fd9b22ad',
    messagingSenderId: '971546956248',
    projectId: 'mhx-attendance-dev',
    authDomain: 'mhx-attendance-dev.firebaseapp.com',
    storageBucket: 'mhx-attendance-dev.firebasestorage.app',
    measurementId: 'G-7BVJF40PNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC1uKe_8kkZ5Mpjk9x20s7p6WlCHV3_qE',
    appId: '1:971546956248:android:03af8a7e1423b6309b22ad',
    messagingSenderId: '971546956248',
    projectId: 'mhx-attendance-dev',
    storageBucket: 'mhx-attendance-dev.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPMHmOvK_NundTRLLYkoppIUSk7sVOqL8',
    appId: '1:971546956248:web:a135c0f0b738c8739b22ad',
    messagingSenderId: '971546956248',
    projectId: 'mhx-attendance-dev',
    authDomain: 'mhx-attendance-dev.firebaseapp.com',
    storageBucket: 'mhx-attendance-dev.firebasestorage.app',
    measurementId: 'G-57LVL4CPHD',
  );
}
